# Generated by Django 3.1 on 2020-08-29 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listing_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='owner_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listing_owner', to='auctions.user'),
            preserve_default=False,
        ),
    ]
