# Generated by Django 3.1 on 2020-08-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200829_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='highest_bidder',
            field=models.IntegerField(blank=True),
        ),
    ]
