# Generated by Django 3.1 on 2020-08-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200830_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bids',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
