# Generated by Django 3.1 on 2020-08-30 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20200830_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='user',
        ),
    ]
