# Generated by Django 3.1 on 2020-08-30 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_bids_listing_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='content',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='description',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='detail_one',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='detail_three',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='detail_two',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='starting_bid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='title',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='listing_id',
        ),
    ]
