# Generated by Django 3.1 on 2020-09-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20200830_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.CharField(default='https://images.unsplash.com/photo-1525610268297-344cdb8dc9af?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', max_length=256),
        ),
    ]
