# Generated by Django 3.1 on 2020-09-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20200902_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchList',
            field=models.ManyToManyField(blank=True, related_name='watchLists', to='auctions.WatchList'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.URLField(default='https://images.unsplash.com/photo-1525610268297-344cdb8dc9af?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', max_length=256),
        ),
    ]
